# Emacs
alias emacs='/Applications/Emacs.app/Contents/MacOS/Emacs "$@"'

alias l='ls'
alias ll='ls -l'
alias m='make'
alias c='g++ -Wextra -Wunused-variable -Wuninitialized --std=c++17'
alias gs='git status'
alias gl='git log --numstat'
alias gd='git diff --cached'
