# Emacs
alias e='emacsclient -a "" -t'
alias eg='emacsclient -a "" -c -n'
alias ek='emacsclient -e "(save-buffers-kill-emacs)"'

alias l='ls'
alias ll='ls -l'
alias m='make'
alias c='g++ -O2 -Wextra -Wunused-variable -Wuninitialized --std=c++17'
alias gs='git status'
alias gl='git log --numstat'
alias gd='git diff --cached'
alias v='vim'
