# Emacs
alias emacs='/Applications/Emacs.app/Contents/MacOS/Emacs "$@"'
alias uw='ssh -Y _@linux.student.cs.uwaterloo.ca'

alias l='ls'
alias ll='ls -l'
alias m='make'
alias gs='git status'
alias gl='git log --numstat'
alias gd='git diff --cached'
